<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot Condition="'$(PublishAot)' == ''">false</PublishAot>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AdvancedSharpAdbClient" Version="3.3.12" />
      <PackageReference Include="Spectre.Console" Version="0.49.0" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource
                Include="Assets/Settings.apk.gz"
                LogicalName="Settings.apk.gz"/>
        <EmbeddedResource Include="Assets/adb-windows/**/*"
                Condition="('$(RuntimeIdentifier)' == 'win-x64' or '$(RuntimeIdentifier)' == 'win-x86') or ('$(RuntimeIdentifier)' == '' and $([MSBuild]::IsOSPlatform('Windows')) and '$(PROCESSOR_ARCHITECTURE)' != 'ARM64')"
                LogicalName="$([System.String]::Copy('%(RelativeDir)').Replace('\','/'))%(Filename)%(Extension)"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="tests/**/*.cs" />
    </ItemGroup>
</Project>
